t ?= esp32
s ?= uk101

ifeq ($t, esp32)
BOARD := node32s
UPLOAD_SPEED := 921600
CPPFLAGS = -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
        -DTFT_RST=-1 -DTFT_WIDTH=240 -DTFT_HEIGHT=320 \
        -DSPI_FREQUENCY=40000000 -DLOAD_GLCD
LIBRARIES = TFT_eSPI FS SPIFFS
endif

ifeq ($t, esp8266)
BOARD := d1_mini
UPLOAD_SPEED := 921600
FLASH_SIZE := 4M1M
F_CPU := 80
CPPFLAGS = -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 \
	-DTFT_DC=PIN_D1 -DTFT_RST=-1 -DTFT_WIDTH=240 -DTFT_HEIGHT=320 \
        -DSPI_FREQUENCY=40000000 -DLOAD_GLCD
LIBRARIES = TFT_eSPI
endif

ifeq ($t, tivac)
BOARD := EK-LM4F120XL
CPPFLAGS = -DHARDWARE_H=\"hw/lm4f-utft-sd.h\"
LIBRARIES = UTFT SD SpiRAM
endif

ifeq ($s, uk101)
CPPFLAGS += -DUK101
SPIFFS_DIR := uk101/programs
endif

ifeq ($s, ohio)
CPPFLAGS += -DOHIO
SPIFFS_DIR := ohio/programs
endif

include $t.mk
