t ?= esp32
s ?= uk101
p ?= programs/$s

FS_DIR := $p
LIBRARIES = SimpleTimer PS2KeyRaw
CPPFLAGS = -DSIMPLE_TIMER_MICROS
CPPFLAGS += -DDEBUGGING=0xff

ifeq ($t, rp2040)
BOARD := adafruit_feather_dvi
FLASH := 8388608_2097152
TERMINAL_SPEED := 115200
CPPFLAGS += -DDVI_BIT_DEPTH=1 -DDVI_RESOLUTION=DVI_RES_640x240p60
LIBRARIES += LittleFS PicoDVI Adafruit_GFX Adafruit_BusIO Wire
endif

ifeq ($t, esp32)
UPLOADSPEED := 921600
LIBRARIES += FS SPIFFS Network
TERMINAL_SPEED := 115200

ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
TERMINAL_EXTRA_FLAGS := -C serialout.txt
SERIAL_PORT := /dev/ttyACM0
CPPFLAGS += -DVGA_BIT_DEPTH=1 -DVGA_RESOLUTION=VGAMode::MODE640x480
LIBRARIES += ESP32Lib SD

else ifeq ($b, olimex)
BOARD := esp32-sbc-fabgl
TERMINAL_EXTRA_FLAGS := -C serialout.txt
SERIAL_PORT := /dev/ttyUSB0
DebugLevel := verbose
CPPFLAGS += -DVGA_BIT_DEPTH=1 -DVGA_RESOLUTION=VGAMode::MODE640x480 -DVGA_FONT=Font8x8
LIBRARIES += ESP32Lib SD

else
BOARD := lolin32
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
        -DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD -DHARDWARE_H=\"hw/esp32-example.h\"
LIBRARIES += TFT_eSPI
endif
endif

ifeq ($t, esp8266)
BOARD := d1_mini
BAUD := 921600
TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
EESZ := 4M2M
XTAL := 80
F_CPU := 80
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD -DHARDWARE_H=\"hw/esp8bit.h\"
LIBRARIES += TFT_eSPI FS LittleFS
endif

ifeq ($t, tivac)
BOARD := EK-LM4F120XL
CPPFLAGS += -DHARDWARE_H=\"hw/stellarpad-example.h\"
LIBRARIES += UTFT SD
endif

ifeq ($s, uk101)
CPPFLAGS += -DUK101
endif

ifeq ($s, ohio)
CPPFLAGS += -DOHIO
endif

include $t.mk
